import daisyui from "daisyui";

/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{ts,html,scss}"],
  theme: {
    extend: {
      fontFamily: {
        sans: [
          "Roboto",
          "system-ui",
          "-apple-system",
          "Segoe UI",
          "Microsoft YaHei",
          "sans-serif",
        ],
      },
    },
  },
  plugins: [daisyui],
  daisyui: {
    // 6 个 MC 风格色系 × light/dark = 12 个主题
    // 命名规则：<色系>-<明暗>，如 grass-light / grass-dark
    themes: [
      // ===== 草绿 Grass（Minecraft 草方块，默认） =====
      {
        "grass-light": {
          primary: "#5a9216",
          "primary-content": "#ffffff",
          secondary: "#85c43b",
          "secondary-content": "#1a2e00",
          accent: "#3d6b06",
          "accent-content": "#ffffff",
          neutral: "#2a3318",
          "neutral-content": "#d4e0b8",
          "base-100": "#fafaf5",
          "base-200": "#f0efe2",
          "base-300": "#d9d8c2",
          "base-content": "#2a3318",
          info: "#3abff8",
          success: "#5a9216",
          warning: "#fbbd23",
          error: "#c53030",
          "--rounded-box": "1rem",
          "--rounded-btn": "0.5rem",
          "--rounded-badge": "1.9rem",
        },
        "grass-dark": {
          primary: "#85c43b",
          "primary-content": "#1a2e00",
          secondary: "#5a9216",
          "secondary-content": "#ffffff",
          accent: "#a8e055",
          "accent-content": "#1a2e00",
          neutral: "#1a2010",
          "neutral-content": "#b8c894",
          "base-100": "#1a2010",
          "base-200": "#232a16",
          "base-300": "#2f3a1f",
          "base-content": "#d4e0b8",
          info: "#3abff8",
          success: "#85c43b",
          warning: "#fbbd23",
          error: "#ef5350",
          "--rounded-box": "1rem",
          "--rounded-btn": "0.5rem",
          "--rounded-badge": "1.9rem",
        },
      },
      // ===== 钻石蓝 Diamond（钻石方块） =====
      {
        "diamond-light": {
          primary: "#17a2b8",
          "primary-content": "#ffffff",
          secondary: "#4dd0e1",
          "secondary-content": "#00363c",
          accent: "#0d7a8a",
          "accent-content": "#ffffff",
          neutral: "#1a3a42",
          "neutral-content": "#b8e0e6",
          "base-100": "#f5fcfd",
          "base-200": "#e2f4f7",
          "base-300": "#c5e8ee",
          "base-content": "#1a3a42",
          info: "#3abff8",
          success: "#17a2b8",
          warning: "#fbbd23",
          error: "#c53030",
          "--rounded-box": "1rem",
          "--rounded-btn": "0.5rem",
          "--rounded-badge": "1.9rem",
        },
        "diamond-dark": {
          primary: "#4dd0e1",
          "primary-content": "#00363c",
          secondary: "#17a2b8",
          "secondary-content": "#ffffff",
          accent: "#7ce5f0",
          "accent-content": "#00363c",
          neutral: "#0f2329",
          "neutral-content": "#9cced6",
          "base-100": "#0f2329",
          "base-200": "#163038",
          "base-300": "#1f4350",
          "base-content": "#b8e0e6",
          info: "#3abff8",
          success: "#4dd0e1",
          warning: "#fbbd23",
          error: "#ef5350",
          "--rounded-box": "1rem",
          "--rounded-btn": "0.5rem",
          "--rounded-badge": "1.9rem",
        },
      },
      // ===== 下界紫 Nether（下界合金/末影） =====
      {
        "nether-light": {
          primary: "#7c3aed",
          "primary-content": "#ffffff",
          secondary: "#a78bfa",
          "secondary-content": "#2e1065",
          accent: "#5b21b6",
          "accent-content": "#ffffff",
          neutral: "#2e1065",
          "neutral-content": "#ddd6fe",
          "base-100": "#faf8ff",
          "base-200": "#f0ebff",
          "base-300": "#ddd0f7",
          "base-content": "#2e1065",
          info: "#3abff8",
          success: "#7c3aed",
          warning: "#fbbd23",
          error: "#c53030",
          "--rounded-box": "1rem",
          "--rounded-btn": "0.5rem",
          "--rounded-badge": "1.9rem",
        },
        "nether-dark": {
          primary: "#a78bfa",
          "primary-content": "#2e1065",
          secondary: "#7c3aed",
          "secondary-content": "#ffffff",
          accent: "#c4b5fd",
          "accent-content": "#2e1065",
          neutral: "#1a0f2e",
          "neutral-content": "#c4b5fd",
          "base-100": "#1a0f2e",
          "base-200": "#251642",
          "base-300": "#33205a",
          "base-content": "#ddd6fe",
          info: "#3abff8",
          success: "#a78bfa",
          warning: "#fbbd23",
          error: "#ef5350",
          "--rounded-box": "1rem",
          "--rounded-btn": "0.5rem",
          "--rounded-badge": "1.9rem",
        },
      },
      // ===== 红石红 Redstone =====
      {
        "redstone-light": {
          primary: "#dc2626",
          "primary-content": "#ffffff",
          secondary: "#f87171",
          "secondary-content": "#450a0a",
          accent: "#991b1b",
          "accent-content": "#ffffff",
          neutral: "#450a0a",
          "neutral-content": "#fecaca",
          "base-100": "#fffafa",
          "base-200": "#feeaea",
          "base-300": "#fcd5d5",
          "base-content": "#450a0a",
          info: "#3abff8",
          success: "#dc2626",
          warning: "#fbbd23",
          error: "#991b1b",
          "--rounded-box": "1rem",
          "--rounded-btn": "0.5rem",
          "--rounded-badge": "1.9rem",
        },
        "redstone-dark": {
          primary: "#f87171",
          "primary-content": "#450a0a",
          secondary: "#dc2626",
          "secondary-content": "#ffffff",
          accent: "#fca5a5",
          "accent-content": "#450a0a",
          neutral: "#1f0808",
          "neutral-content": "#fca5a5",
          "base-100": "#1f0808",
          "base-200": "#2e0f0f",
          "base-300": "#421616",
          "base-content": "#fecaca",
          info: "#3abff8",
          success: "#f87171",
          warning: "#fbbd23",
          error: "#ef5350",
          "--rounded-box": "1rem",
          "--rounded-btn": "0.5rem",
          "--rounded-badge": "1.9rem",
        },
      },
      // ===== 金苹果 Gold =====
      {
        "gold-light": {
          primary: "#d97706",
          "primary-content": "#ffffff",
          secondary: "#fbbf24",
          "secondary-content": "#451a03",
          accent: "#b45309",
          "accent-content": "#ffffff",
          neutral: "#451a03",
          "neutral-content": "#fde68a",
          "base-100": "#fffcf5",
          "base-200": "#fff4e0",
          "base-300": "#fbe5b8",
          "base-content": "#451a03",
          info: "#3abff8",
          success: "#d97706",
          warning: "#fbbd23",
          error: "#c53030",
          "--rounded-box": "1rem",
          "--rounded-btn": "0.5rem",
          "--rounded-badge": "1.9rem",
        },
        "gold-dark": {
          primary: "#fbbf24",
          "primary-content": "#451a03",
          secondary: "#d97706",
          "secondary-content": "#ffffff",
          accent: "#fcd34d",
          "accent-content": "#451a03",
          neutral: "#1f1305",
          "neutral-content": "#fcd34d",
          "base-100": "#1f1305",
          "base-200": "#2e1d0b",
          "base-300": "#422a12",
          "base-content": "#fde68a",
          info: "#3abff8",
          success: "#fbbf24",
          warning: "#fbbd23",
          error: "#ef5350",
          "--rounded-box": "1rem",
          "--rounded-btn": "0.5rem",
          "--rounded-badge": "1.9rem",
        },
      },
      // ===== 末影黑 End（深色优雅） =====
      {
        "end-light": {
          primary: "#1f2937",
          "primary-content": "#a7f3d0",
          secondary: "#6b7280",
          "secondary-content": "#ffffff",
          accent: "#059669",
          "accent-content": "#ffffff",
          neutral: "#111827",
          "neutral-content": "#d1d5db",
          "base-100": "#fafafa",
          "base-200": "#f4f4f5",
          "base-300": "#e4e4e7",
          "base-content": "#18181b",
          info: "#3abff8",
          success: "#059669",
          warning: "#fbbd23",
          error: "#dc2626",
          "--rounded-box": "1rem",
          "--rounded-btn": "0.5rem",
          "--rounded-badge": "1.9rem",
        },
        "end-dark": {
          primary: "#34d399",
          "primary-content": "#022c22",
          secondary: "#6b7280",
          "secondary-content": "#ffffff",
          accent: "#a7f3d0",
          "accent-content": "#022c22",
          neutral: "#0a0a0a",
          "neutral-content": "#d1d5db",
          "base-100": "#0a0a0a",
          "base-200": "#161616",
          "base-300": "#262626",
          "base-content": "#e4e4e7",
          info: "#3abff8",
          success: "#34d399",
          warning: "#fbbd23",
          error: "#ef5350",
          "--rounded-box": "1rem",
          "--rounded-btn": "0.5rem",
          "--rounded-badge": "1.9rem",
        },
      },
    ],
    // 默认暗色主题指向 grass-dark
    darkTheme: "grass-dark",
  },
};
